version: "3.5"
services:
  backend:
    image: thedejavu/bestside-backend:main
    ports:
      - 8000:8000
    environment:
      APP_ENV: production
      BITSTAMP_BASE_URL: "https://www.bitstamp.net/api/v2"
      GEMINI_BASE_URL: "https://api.gemini.com/v2"
      BLOCKCHAIN_DOT_COM_BASE_URL: "https://api.blockchain.com/v3/exchange"
      BITFINEX_BASE_URL: "https://api-pub.bitfinex.com/v2"

  frontend:
    image: thedejavu/bestside-frontend:main
    ports:
      - 3000:3000
    environment:
      APP_ENV: production
      REACT_APP_WEBSOCKET_URL: "ws://147.182.182.117:8000/ws"

  nginx: 
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/error.log:/etc/nginx/error_log.log
      - ./nginx/cache/:/etc/nginx/cache
    ports:
      - 80:80
      - 443:443