version: "3.5"
services:
  backend:
    container_name: bestside_exchange_backend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/src/app
    ports:
      - 8000:8000
    environment:
      APP_ENV: development

  frontend:
    container_name: bestside_exchange_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - "./:/app"
      - "/app/node_modules"
    ports:
      - 3000:80
    environment:
      APP_ENV: development
